### ISSUE TITLE
example of postgres connection

### ISSUE THREAD

**Issue by tschuettenberg** [MarcoDuiker/QGIS_Map_library#10]
Hi,
could you please provide an example of a valid connection for the postgres provider?
Using the datasource from the .qlr like the following does not work.

`"connection": "service='produkte' authcfg=user440 key='gid' estimatedmetadata=true srid=25832 type=MultiPolygon checkPrimaryKeyUnicity='1' table=maplibrary.wahlbezirke (geom)",`

_Why not using the easy .qlr (anymore)? - I would like to load directly from the db including the saved default styles, because I'm trying to combine the use of maplibrary and pgMetadata (https://github.com/3liz/qgis-pgmetadata-plugin). In this way I can reuse my existing postgis maplibrary qlrs._

Best regards

**Comment by MarcoDuiker** [comment]
You need to set `provider` to `postgres`.
`connection` can be set according the docs on https://docs.qgis.org/3.16/en/docs/pyqgis_developer_cookbook/loadlayer.html#id1 (scroll down to bullet "PostGIS database").

It is easiest to try out from the console. When it's working, copy the connection string to the library.

**Comment by tschuettenberg** [comment]
`"provider": "postgres"` is/was set.

Well, the following produces a layer connection like I had in the qlr (appart from type and srid) when using the QGIS python console:
```
uri = QgsDataSourceUri()
uri.setConnection("produkte", None, None, None, authConfigId="user440")
uri.setDataSource("maplibrary", "wahlbezirke", "geom", aKeyColumn="gid")
vlayer = QgsVectorLayer(uri.uri(False), "Wahlbezirke", "postgres")

QgsProject.instance().addMapLayer(vlayer)
```
But pasting this into the maplibrary connection: 
```
"connection": "uri = QgsDataSourceUri() uri.setConnection(\"produkte\", None, None, None, authConfigId=\"user440\") uri.setDataSource(\"maplibrary\", \"wahlbezirke\", \"geom\", aKeyColumn=\"gid\") vlayer = QgsVectorLayer(uri.uri(False), \"Wahlbezirke\", \"postgres\")"
``` 

results in an invalid layer _(`CRITICAL    Layer ist ungültig : Der Layer uri = QgsDataSourceUri() uri.setConnection("produkte", None, None, None, authConfigId="user440") uri.setDataSource("maplibrary", "wahlbezirke", "geom", aKeyColumn="gid") vlayer = QgsVectorLayer(uri.uri(False), "Wahlbezirke", "postgres") ist kein gültiger Layer und kann nicht zur Karte hinzugefügt. Grund: `)_.

Any further hints?

**Comment by MarcoDuiker** [comment]
From the console:

```
uri = QgsDataSourceUri()
uri.setConnection("produkte", None, None, None, authConfigId="user440")
uri.setDataSource("maplibrary", "wahlbezirke", "geom", aKeyColumn="gid")
print(uri.uri())
```

Use the printed result like:

```
"connection": "uri =printed_result_goes_here"
```

**Comment by tschuettenberg** [comment]
So it basically is the known connection string, prepended with `uri = `.
However, the database connection fails from maplibrary, no matter if authcfg and service are used or the full detailed credentials. From python console any (valid) combination work.

**Comment by MarcoDuiker** [comment]
Are there any error messages? 
What do the postgresql logs say?

**Comment by tschuettenberg** [comment]
In the QGIS error message panel for PostGIS when using authcfg it says: "FATAL: Passwort-Authentifizierung f�r Benutzer �b4406621� fehlgeschlagen"  (password authentification failled). - So, the authcfg-ID is correclty resolved, but seams not to be applied.
When using the normal credentials it says: "FATAL: Datenbank �b4406621� existiert nicht" (database does not exist), which is wrong, because b406621 is a username.
Or this might be an encoding issue, because of the strange chars in the error messages?
Btw, I'm on QGIS 3.16.6 and maplibrary 1.1

**Comment by MarcoDuiker** [comment]
To rule out any encoding issues you can try to add the layer from the console using the connection string. So use something like:

```
layer = iface.addVectorLayer( connection_string_goes_here, 
                                               'just any layer name', 
                                               'postgres')
```

Please report if you have any success with this.

**Comment by tschuettenberg** [comment]
This works flawlessly from the console (like the other console methods), if "schema"."viewname" stay in double quotes (` " `).

**Comment by MarcoDuiker** [comment]
It would help if you could share the connection string here. You can obscure any info that you don't want to share by replacing with `*` or `x`.

**Comment by tschuettenberg** [comment]
no problem, see above:
```
uri = QgsDataSourceUri()
uri.setConnection("produkte", None, None, None, authConfigId="user440")
uri.setDataSource("maplibrary", "wahlbezirke", "geom", aKeyColumn="gid")
print(uri.uri(False))
```
results in the followig connection string:
```
service='produkte' authcfg=user440 key='gid' table="maplibrary"."wahlbezirke" (geom)
```
using in the console works:
```
layer = iface.addVectorLayer('service=produkte authcfg=user440 key=gid table="maplibrary"."wahlbezirke" (geom)', 'just any layer name', 'postgres')
```
but not working in maplibrary json:
```
"connection": "uri = service=produkte authcfg=user440 key=gid table=\"maplibrary\".\"wahlbezirke\" (geom)"
"connection": "uri = service=produkte authcfg=user440 key=gid table=maplibrary.wahlbezirke (geom)"
"connection": "uri = service=produkte authcfg=user440 key=gid table='maplibrary'.'wahlbezirke' (geom)"
```

**Comment by MarcoDuiker** [comment]
Oops ... you need to skip the `uri =` part.
That should not be in the connection string.
(Sorry, having holidays)

**Comment by tschuettenberg** [comment]
Oh dear, what a round trip! :-) 
So I end up where I started, i.e. with the usual and known PostGIS connection string. Exept that I must not eliminate the double quotes, instead make them single quotes! - Sorry, silly me, I could have found that by trial and error.

Side effect: if the connection string also contains the table's geometry type, the existing default style is pulled from the db, too.
Sorry for the noise, happy holiday!
