### ISSUE TITLE
Auto-Reload functionality for libraries

### ISSUE THREAD

**Issue by olivergrimm** [MarcoDuiker/QGIS_Map_library#11]
The idea is to add a functionality to have a timer based reload of the libraries. The main goal is to prevent the need to reopen QGIS in the case of a change in a library.

I would like to fix this issue right away @MarcoDuiker would you be willing to review a pull request implementing these change?

**Comment by MarcoDuiker** [comment]
I am not a big fan of default automatic checking and reloading.

I'd like to suggest to implement:
- a menu item to manually check for library updates (and of course reload when new)
- an item in the settings dialog which enables the user to specify a time interval for checking and reloading

Would that work for you? If so, I'm happy to see a PR coming.

**Comment by olivergrimm** [comment]
allright. We suggest to make this setting optional and available in libs.json. So there is only an autoreload if the entry exists.
