### ISSUE TITLE
Filter the layer tree according to the search term

### ISSUE THREAD

**Issue by MiraGeowerkstatt** [MarcoDuiker/QGIS_Map_library#3]
When working with large layer trees in Map Library, finding the desired layer in a search can become somewhat tedious.  My proposal is to filter the layer tree according to the search term and support navigating the search results with the up / down arrow keys.

I would like to fix this issue right away @MarcoDuiker  would you be willing to review a pull request implementing these changes?

**Comment by MarcoDuiker** [comment]
This sounds like an interesting idea. I am willing to review a pull request. 

Please make this functionality configurable in the settings dialog. So users can choose between "old" behavior and "new" behavior and keep things nicely backwards compatible.

**Comment by MiraGeowerkstatt** [comment]
Great, thank you. I will make it configurable.
